# Generated by Django 2.0 on 2018-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181118_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_dealer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
