# Generated by Django 2.0 on 2018-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_schemes_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('seo_name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_seo_name', models.TextField(null=True)),
                ('product_mrp', models.IntegerField(null=True)),
                ('product_discount', models.FloatField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_description', models.TextField(default=None)),
                ('product_features', models.TextField(default=None)),
                ('product_image_url', models.URLField(default=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='schemes',
            name='seo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
