# Generated by Django 2.0 on 2018-09-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_auto_20180922_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_module.Category'),
        ),
    ]
