# Generated by Django 2.0 on 2018-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image_url',
            field=models.FilePathField(default=None),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='image_url',
            field=models.FilePathField(default=None),
        ),
    ]
