# Generated by Django 2.0 on 2018-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_auto_20180922_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image_url',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='image_url',
            field=models.TextField(default=None),
        ),
    ]
