# Generated by Django 2.0 on 2019-01-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_module', '0007_auto_20190106_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_summary', models.TextField()),
                ('order_completed', models.BooleanField(default=False)),
                ('order_comments', models.TextField()),
                ('order_date', models.DateTimeField()),
                ('order_completed_date', models.DateTimeField()),
                ('order_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='mapped_variant',
            field=models.ManyToManyField(blank=True, to='home_module.Variants'),
        ),
    ]
